= Thoughts

- Should (certain) Activities (Tasks / Issues) have a Status (like: Open, Closed,  ...)?
If closed, make them less relevant in search
- Use commands for everything, like:
- add new project
- add new book
- rename identifier
- add identifier
- deactivate identifier (no longer available for activity)
- remove identifier (no longer available for activity)
- Use the activity identifier, to connect additional information.
An example could be cooking recipes. This way the recipe can be stored separately from the activity logbook, but easily found back.
Activity `cooking.recipe.hungarian-goulash`
Add the recipe file `recipe-hungarian-goulash.hjson`, with additional content:
+
----
    {
        identifier: hungarian-goulash
        url: https://www.daringgourmet.com/traditional-hungarian-goulash-gulyas
        ingredients: [
            3 tablespoons pork lard, or butter (pork fat is traditionally used and highly recommended for the best flavor)
            1 1/2 pounds yellow onions chopped
            1/4 cup good quality sweet imported Hungarian paprika
            etc, etc
        ]
        steps: [
            Melt the lard or butter in a Dutch oven over medium high heat and cook the onions until beginning to brown, about 7-10 minutes. Remove from heat and stir in the paprika. Add the beef and garlic, return to the heat, and cook for about 10 minutes, or until the beef is no longer pink.
            Add the bell peppers and cook for another 7-8 minutes. Add the carrots, tomatoes, potatoes, beef broth, bay leaf, salt and pepper. Bring to a boil, cover, reduce the heat to medium, and simmer for 40 minutes (see note). Add salt to taste.
        ]
        notes: [
          	If you're using a tougher cut of beef like chuck or round, cook the beef first, without the carrots, tomatoes, potatoes and bell peppers, for 30-45 minutes, then add the vegetables and cook for another 40 minutes until the beef is tender.  A well-marbled cut like chuck will produce the most flavor while a leaner cut will cook faster.  Your choice.
        ]
    }
----

- Convert url to known activity
When reading a book online, and quickly want to create an activity that represent that you start or stop reading,
it would be nice to just use the url as activity identifier.
The app needs to scan, what hostname is used, and what kind of activities are related to that. Here 'manning.com'
is specified in the file `publisher-manning.hjson`. There are also all known book url's stored.
+
----
$ app  https://livebook.manning.com/book/testing-angular-applications/chapter-2

$ app  https://livebook.manning.com/book/testing-angular-applications/chapter-2  start
----

- Start reading next chapter of a book
When reading a book, and tracking which chapters you've already red, then continue reading on the next chapter,
should be made easy.
+
[NOTE]
====
This is possibler, because the book is known as url `https://livebook.manning.com/book/testing-angular-applications` so only the part `chapter-3` is new.

----
$ activity-tracker  https://livebook.manning.com/book/testing-angular-applications/chapter-3  add
$  created  new identifier  self.study.book.testing-angular-applications.chapter-3
$ activity-tracker  https://livebook.manning.com/book/testing-angular-applications/chapter-3  start

$ activity-tracker  https://livebook.manning.com/book/testing-angular-applications/chapter-2  next
----
====

- Support input / output with https://www.iana.org/assignments/media-types/media-types.xhtml[Media Types].
