/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.verhagen.activitylogbook.app;

import com.github.verhagen.activitylogbook.core.Engine;

public class App {


    public static void main(String[] args) {
    }


    
}
