= Progress


== General Action List

- [ ] Update description of Activity:
+
* 🧑‍💻 author
* 🌍 location
+
Add author data to `~/activity-tracker/activity-tracker-configuration.hjson`
+
If author is not set, use the system default `${user.name}`
+
Add location data to `~/.activity-tracker/locations.hjson`
+
Locations are used in Activity Tracker Events, as well as in Activity Logbook Events.

- [ ] Convert documentation from MarkDown into AsciiDoc  
      Convert MarkDown to AsciiDoc  
      https://matthewsetter.com/technical-documentation/asciidoc/convert-markdown-to-asciidoc-with-kramdoc/


- [x] Implement loading of _project data_ (from files `projects-*.hjson`) for activity identifiers
- [x] Implement loading of _book data_ (from files `publisher-*.hjson`) for activity identifiers
- [ ] Make Activity a DP:Composite, so collections of activities can be created.
      NOTE: _This probably holds for the ActivityTrackerEvents as well as for the ActivityLogbookEvents_
- [ ] Create 'snapshot' from data: projects-\*.hjson, books-\*.hjson, etc and activity-logbooks.csv / md
      Each snapshot should work, give correct results.
      
- [ ] Rename Identifiers like `project.mazes-for-programmers` into `project.mazes-for-programmers-java`  
      Update all ActivityLogbook entries and ActivityLogEntries since last snapshot
      Record rename(s) activities.


== IdentifierRegistry Action List

- [ ] Rename IdentifierRegistry in to IdentifierCatalog
- [x] Add IdentifierRegistry with search(query)
- [ ] IdentifierRegistry - show most relevant on top (last used identifiers in Activity Logbook and / or Activity Log instances)
- [ ] IdentifierRegistry - filter out certain identifiers, because they are no longer relevant.
      For Example: `client-abc.*`
      

== ActivityLogbook Action List

- [ ] Validate identifiers 'project.project.abc' against IdentifierRegistery
- [ ]


- [ ] Create ActivityLogEntry every Activity has a start and stop moment (on a certain day)
- [ ] Register Tags, search by tag name(s)


== Conversion Action List

- [ ] Conversion of ActivityEntry to Activity


== Activity Filters Action List

- [ ] From the collection of activities, filter by identifier
- [ ] From the collection of activities, filter by start date (and time) and end date (and time)
