/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.7.1/userguide/multi_project_builds.html
 */

rootProject.name = "atnb"
include(
	"atnb-app"
	, "atnb-book"
	, "atnb-core"
	, "atnb-cucumber"
	, "atnb-domain"
	, "atnb-grammar"
	, "atnb-issue"
	, "atnb-opportunity"
	, "atnb-project"
	, "atnb-app-monolith"
)
