/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.verhagen.activitylogbook.java-application-conventions")
}

dependencies {
    implementation(project(":activity-logbook-domain"))
    implementation(project(":activity-logbook-book"))
    implementation(project(":activity-logbook-project"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.github.verhagen.activitylogbook.app.App")
}
