/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.verhagen.activitylogbook.java-library-conventions")
}

dependencies {
    implementation("com.vladsch.flexmark:flexmark-all:0.62.2")
}
