= Activity Logbook Event

An activity consists of six things:

- 📅 Date and Time - When
+
This is required. It represents a moment in time. On which day the activity takes place.
- 🆔 Identifier - What
+
This is required, and identifies what the activity is about.
- ⏳ Duration
+
This is optional, but very useful! It tells how much time is spent on the activity.
- 📋 Note
+
This is optional. It can be used to give some additional information about the activity.
- 🧑 Author - Who
- 🧭 Location - Where


=== When

When writing down activities, this is mostly done on a daily base. This makes it easy to see, if
a new entry was already made for a particular day.

This makes it possible to lookup when time has been spent on a certain activity.

Date information should be given as `<year>.<month>.<day>` like `2020.12.01` for Tuesday 1 December 2020.


== Identifier

An activity must have an identifier. Some examples of an activity could be: `cooking`, `working`, `running`, `study`.
These are very generic activities, which is OK, but to make them more useful a more specific identifier is better.
Maybe one likes to read back what was cooked on a certain moment. Maybe it was __goulash__ or __spätzle__, these identifiers
would become `cooking.goulash` and `cooking.spätzle`. This way one can find back when what was cooked, but also how many times,
it has been cooked this month, in the last 90 days, or this year.

But maybe it's interesting to know which cooking recipes have been used? So different goulash recipes can be found back.
Or some recipes are used again and again, one can easy find back the most cooked recipes, maybe ones favorites?

For studying a certain subject, one is probable reading a particular book. Reading the complete book, probably takes multiple
moments. Each of these moments can be seen as an activity (log) entry. Maybe one likes to record which chapter
is being red?

`reading.book.mythical-man-month.chapter-6`

By using activities with the same identifier, one can see how many times, time has been spent on that activity.
When both the moment of starting the activity, as well as the moment of stopping the activity are entered, the duration
can be calculated. Which makes it poossible to calculate the total time spent on an activity.
Also by doing activities that begin with the same identifier, say 'cooking'. The total amount of time spent on that type of
activity can be easily calculated.


== Activity Duration

Each activity takes an amount of time. When this is added to the activity, it's possible to see how much time is spent on
an activity, every day, or in total per week or per month. Or compare which cooking recipes take less time or which ones take
more time. Or see if one repeats a certain activity like cooking a specific recipe, that it will be taking less time? Or
finding out the progress of reading a particular book.

Duration of an activity can be given in hour and minutes, using the format `<hours>:<minutes>`. A shortcut us just entering
`<hours>` or only `:<minutes>`. Some examples:

`:30` - 30 minutes 
`1:30` - 1 hour and 30 minutes
`:90` - 90 minutes, could have been entered as `1:30` as well.

In the end the time spent on an activity is the most important part, but maybe it's also interesting to record when the
activity started and stopped. In that case use a time stamp, for starting and stopping the activity. Starting and stopping
an activity can be given as moment in `hour:minutes`.

`9:30-10:15` - Started at 9:30 and ended at 10:15 in the morning, working on an activity.
`17:45-18:30` - Started at 17:45 and stopped at 18:30 in afternoon / evening, working on an activity.


== Activity Note

Additional information can be written as note with the activity.


== Why writing down activities is useful

Once all kind of activities are written down, answers to certain questions can be found, like:

- How much time has been spent on cooking or studying this week / month / semester / etc
- How much time did it take to read the book *The Mythical Man-Month* (so far).  
  If additional information would be available about which chapters are in the book, one can even make an progress indication. Or
  maybe even make an estimate how much time it probably will take to finish reading the book.


== Some Examples

To make entering activities quick, easy and readable and not related to a specific tool, they can be stored as plain text.

Some plain text, each row represents an Activity

----
2020.12.01 :45 reading.book.mythical-man-month
2020.12.01 9:30-10:15 reading.book.mythical-man-month.chapter-6 Half way the chapter.
----

Some Markdown formatted text, containing activities as unordered list entries, where the duration or start-stop time and activity
identifier is given between square brackets. After the brackets, the optional note. All activities are per day, entered under a
heading 2, here `== 2020.12.01 Tuesday`.

----
== 2020.12.01 Tuesday
- [:45 reading.book.mythical-man-month]
- [9:30-10:15 reading.book.mythical-man-month.chapter-6] Half way the chapter.
----