/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.verhagen.atnb.java-library-conventions")
}

dependencies {
    api(project(":atnb-domain"))
    implementation("commons-io:commons-io:2.11.0")
}
